Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 50
Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Max: 500

Style/FrozenStringLiteralComment:
  Enabled: false
Style/FrozenStringLiteral:
  Enabled: true

Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false

